### PR TITLE
remove unmaintained react-pure-render

### PR DESCRIPTION
**Pull request by rosskevin**
continuation of PR #114

### CODE REVIEW

**Comment by rosskevin** [comment]
This is rebased and good to go.

**Comment by wookieb** [comment]
Why whole recompose is installed instead simpler package like shallow-equal?

**Comment by rosskevin** [comment]
Because the recompose package contains the function. There is no consequence to the _whole_ package being installed due to tree shaking and a direct reference to the needed file.

**Comment by taion** [comment]
Seems weird to pull in a recompose dep here. Could we bump the min React version and use `React.PureComponent`?

**Comment by rosskevin** [comment]
I've stopped using react-formal due to maintenance concerns.

**Pull request closed without merging**
